### ISSUE TITLE
Spelling mistake correction fallout

### ISSUE THREAD

**Issue by shtukas** [guardian/recipeasy#216]
This commit ( https://github.com/guardian/recipeasy/pull/215 ) has corrected a spelling mistake. We need to check how that actually and exactly affect the model. Also do we now need to correct any corrupted database record containing the incorrect spelling ?

**Comment by LATaylor-guardian** [comment]
@shtukas We really should have checked if something has effected the model and had the possibility of corrupting database records before correcting what to the user is a spelling mistake!

**Comment by shtukas** [comment]
@LATaylor-guardian True. In fact I was being over cautious, we have already done this kind of correction several time without problems. It doesn't affect the model.  

As for the correction, it will be done by the people doing the verification steps (since the incorrectly spelled categories will just show up as empty -- prompting the verifiers to correct it with the correct values).

**Comment by shtukas** [comment]
Ok, so I have fully demonstrated to myself that those tags are indeed just strings and...

1. When the recipe is displayed. Whatever was in the database table is echoed as current value of the field.

2. If what was in the database table is no longer a known tag then the option displays its default (empty value). This happens because currently recorded tag matches none of the source code known tags. So the HTML option displays its default empty value. 

For the future: Correcting (or more likely removing) a tag, will cause all the records carrying that tag to be shown on the curation page with an empty value, even though the corresponding atom will carry what will appear to be a valid (but obsolete) value.
