### ISSUE TITLE
The image deletion button doesn't work

### ISSUE THREAD

**Issue by shtukas** [guardian/recipeasy#272]
The second image ( which is actually a Gif ) on this recipe ( https://recipeasy.capi.gutools.co.uk/recipe/verify/e864c3ae46ec306d4705feb7aa79679f ) should be removed, but the delete button has no effect

**Comment by shtukas** [comment]
Same with this recipe: https://recipeasy.capi.gutools.co.uk/recipe/curate/8c40912b4bb88b1cb2713f68f1abda94

**Comment by annebyrne** [comment]
Resolved with https://github.com/guardian/recipeasy/pull/314
