### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by tsop14** [guardian/recipeasy#47]
The DB model records time in minutes but the ui should allow the user to enter in time or mins. 

Entering in 90mins should automatically become 1hr 30min
- [ ] display time on ui as hours and mins

**Comment by tsop14** [comment]
[times.pdf](https://github.com/guardian/recipeasy/files/514146/times.pdf)

**Comment by tsop14** [comment]
![times](https://cloud.githubusercontent.com/assets/8484757/19158430/934c4040-8be0-11e6-9796-5b26637b4fd1.png)

**Comment by shtukas** [comment]
This is solved.
