### ISSUE TITLE
Hitting enter moves on to the next recipe

### ISSUE THREAD

**Issue by alastairjardine** [guardian/recipeasy#51]

**Comment by tsop14** [comment]
Hitting enter triggers the submit button and posts the form (rather than triggering the skip button)

**Comment by alastairjardine** [comment]
should it do nothing?

**Comment by tsop14** [comment]
(My comment 👆 was clarify the reason why it was moving on to the next recipe.)

I think it should do nothing, or at least do nothing when you are focused on an input field?

NB If a form has a title and all existing ingredients have an `item` field, it can be submitted. So currently it is very easy to trigger a submit long before the user has finished.
