### ISSUE TITLE
Scrollbar strangeness

### ISSUE THREAD

**Issue by alastairjardine** [guardian/recipeasy#54]
Put the scrollbars in the appropriate place :) Scrollbar for recipe detail is attached to structure, making it look a wee bit odd and confusing

![screen shot 2016-10-07 at 14 35 46](https://cloud.githubusercontent.com/assets/4292469/19191717/80bbe6cc-8c9b-11e6-933f-de878fb79df3.png)

**Comment by shtukas** [comment]
Yep, the most outer scrollbar is the page. The inner one controls the form which is has a CSS `    overflow: scroll` against it. I guess that this was done to be able to see the entire form without losing sight of the recipe itself. 

Interestingly the simplest way to solve this would be to put the form on the left hand side. (Not suggesting that we should, just highlighting that this is the simplest/natural way to solve the problem of having the two scroolbars next to each other.)

**Comment by alastairjardine** [comment]
thanks @shtukas. Probalbly does need fixing, as it's a strange UI 'bug' at the moment

**Comment by shtukas** [comment]
This problem has been fixed by @tomrf1 here: https://github.com/guardian/recipeasy/commit/8ecbf037a4f700677c4edf0036aa19453b7e91b5
